/**
 * Extended environment types for Macrodata
 *
 * Note: Env is generated by wrangler types in worker-configuration.d.ts
 * Secrets like BRAVE_SEARCH_API_KEY are set via `wrangler secret put`
 * and are typed as required strings there. The code should handle
 * missing secrets gracefully at runtime.
 */

export {};
